services:
  account:
    image: "codewithaamir/account:v1"
    container_name: account-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m # providing the limit of 700mb for container
    networks: # networks used to communicate the microservices to each other
      - khanbank

  loan:
    image: "codewithaamir/loan:v1"
    container_name: loan-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - khanbank

  card:
    image: "codewithaamir/card:v1"
    container_name: card-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - khanbank
networks:
  khanbank:
    driver: "bridge" # establishing the bridge to the ms communication each other.